### ISSUE TITLE
commsLink multiple connection links

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#21]
So what do you want to change about commsLink. I want to add a last argument to choose which connection link type, but the best way to do this is to change CommNode interface. I want to get any interfaces changes done now before we let people use the code.

Example:

**before:**
`CommsLink *connectionLayer;`
**after:**
`CommsLink *connectionLayer[MAX_CONNCETIONS];`

**before:**
`bool initConnection(transport_protocol_t connectionType, const char* port, const char* address = NULL, uint32_t baudrate = 0);`

**after:**
`bool initConnection(transport_protocol_t connectionType, const char* port, const char* address = NULL, uint32_t baudrate = 0, uint32_t connectionLinkID =0);`

ect...

Which will allow us to init send on a data link like protonet. This would allow a mesh network by using multiple xbee's on one platform reusing the same queue and threads. Would be a slight faster and use less space. 

Did you have better idea?

**Comment by CheezBoiger** [comment]
What is the connection link id for?

**Comment by MichaelWallace30** [comment]
That is the 
`connectionLayer[connectionLinkID]`

So you would do sudo code

`
init(udp ,......., 1);
init(serial,.........2);
init(xbee........3);
addAddress(.......,1);
addAddress(.......,3);
send(message, 1);//send through udp
send(message,2);//send through serial
send(message,3);//send through xbee
`

**Comment by CheezBoiger** [comment]
I feel having one whole mash of connections (UDPs, TCPs, Serial, Zigbee, Digimesh) into one interface is kind of ridiculous, we have to separate them into two different interfaces. One has to be SocketInterface (for UDP and TCP sockets), and the other is SerialInterface (for our Serial, and Zigbee).

I propose making a separate state machine object handle the work, rather than tossing all the storage work on Comms node. At this point we are making a standard node for clients to use, this object is simply just a manager, holding the necessary connections inside. This will be a NetworkGraph that holds an adjacency-list represented graph. An object known as Network will be the front end, taking input such as:
```C++
Network::InitNewProtocol(connect_type, cluster_type, cluster_id);
```
Where socket type is the type of socket (TCP/UDP or whatever else there is), cluster type is the whether it's taking multiple connections or if it is only taking one single connection. 

I'll have to tell you about this tomorrow.


We can't mash all of these connections into an array and call them layers. NetworkGraph will handle the work and store the connections inside the graph. It allows us to determine latency times, along with finding the fastest route to where you plan to send it to. It doesn't matter what type of connection it is (socket or serial) it is actually smart enough to determine where the fastest route to it's destination. 

Like I said, this is something we shouldn't redesign until the future.

**Comment by CheezBoiger** [comment]
I need to go over the details with you on this, and why I need students to help on it. **THIS** is where the real computer science shit begins.

**Comment by CheezBoiger** [comment]
I don't need students to worry about zigbee, tcp, udp, windows and linux sockets. I need to focus their knowledge of computer science in general for this library.

**Comment by CheezBoiger** [comment]
If we decide on your idea, we need to put those in objects instead of in Comms.

**Comment by MichaelWallace30** [comment]
Really we don't have to change any thing at the moment. Right now they can just make multiple connections through multiple instantiation of comms which will work fine. Sound like you want our nodes to be routers. Ok if we do it your way it doesn't seem like we need to change comms interface.  We should just leave comms interface alone and commslink is internal so it would be a drastic change for platforms.

**Comment by CheezBoiger** [comment]
indeed, let's just work with what we got so far. We'll worry about the whole network topology later on. As long as what we got, works, there is no need to break it up again to add something else lulz.
